CREATE DATABASE TECHCHALLENGE;
GO

USE TECHCHALLENGE
GO

CREATE TABLE dbo.CODIGO_AREA_BRASIL (
        DDD CHAR(2) NOT NULL PRIMARY KEY,
        DSESTADO CHAR(2) NOT NULL,
        DSCIDADE NVARCHAR(100) NOT NULL,
        DSREGIAO NVARCHAR(255) NOT NULL,
        DHREGISTRO DATETIME DEFAULT GETDATE()
	);
GO

CREATE TABLE dbo.CONTATO (
        ID INT PRIMARY KEY IDENTITY(1,1),
        NMUSUARIO NVARCHAR(255) NOT NULL,
        NRDDD CHAR(2) NOT NULL,
        NRTELEFONE NVARCHAR(9) NOT NULL,
        DSEMAIL  NVARCHAR(100) NOT NULL,
        DHREGISTRO DATETIME DEFAULT GETDATE(),

        CONSTRAINT FK01_NRDDD_CODIGO_AREA_BRASIL FOREIGN KEY (NRDDD) REFERENCES CODIGO_AREA_BRASIL(DDD)
	);
GO