services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: banco-docker
    environment:
      SA_PASSWORD: "Teste@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./01-BaseTechChallenge.sql:/tmp/01-BaseTechChallenge.sql
      - ./02-BaseTechChallenge.sql:/tmp/02-BaseTechChallenge.sql
      - ./init-basetechchallenge.sh:/tmp/init-basetechchallenge.sh
    command: /bin/bash ./tmp/init-basetechchallenge.sh

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\.aspnet\https:/https:ro
    ports:
      - "8080:8080"
      - "443:443"

  amqpworker:
    build:
      context: .
      dockerfile: Dockerfile-amqpworker
    container_name: worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest