apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus-config
  annotations:
    description: "Configuração do Prometheus para monitoramento da API."
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'api'
        scrape_interval: 5s
        static_configs:
          - targets: ['51.8.253.79:8080']