apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-scripts-config
data:
  01-BaseTechChallenge.sql: |
    IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TECHCHALLENGE')
    BEGIN
        CREATE DATABASE TECHCHALLENGE;
    END
    GO

    USE TECHCHALLENGE
    GO

    DROP TABLE IF EXISTS CODIGO_AREA_BRASIL;
    GO

    CREATE TABLE dbo.CODIGO_AREA_BRASIL (
      DDD CHAR(2) NOT NULL PRIMARY KEY,
      DSESTADO CHAR(2) NOT NULL,
      DSCIDADE NVARCHAR(100) NOT NULL,
      DSREGIAO NVARCHAR(255) NOT NULL,
      DHREGISTRO DATETIME DEFAULT GETDATE()
    );
    GO

    DROP TABLE IF EXISTS CONTATO;
    GO
    
    CREATE TABLE dbo.CONTATO (
            ID INT PRIMARY KEY IDENTITY(1,1),
            NMUSUARIO NVARCHAR(255) NOT NULL,
            NRDDD CHAR(2) NOT NULL,
            NRTELEFONE NVARCHAR(9) NOT NULL,
            DSEMAIL  NVARCHAR(100) NOT NULL,
            DHREGISTRO DATETIME DEFAULT GETDATE(),

            CONSTRAINT FK01_NRDDD_CODIGO_AREA_BRASIL FOREIGN KEY (NRDDD) REFERENCES CODIGO_AREA_BRASIL(DDD)
      );
    GO
  02-BaseTechChallenge.sql: |
    USE TECHCHALLENGE
    GO

    INSERT INTO CODIGO_AREA_BRASIL (DDD, DSESTADO, DSCIDADE, DSREGIAO) VALUES 
            (11, 'SP', 'São Paulo', 'Região Metropolitana de São Paulo/Região Metropolitana de Jundiaí/Região Geográfica Imediata de Bragança Paulista'),
            (12, 'SP', 'São Paulo', 'Região Metropolitana do Vale do Paraíba e Litoral Norte'),
            (13, 'SP', 'São Paulo', 'Região Metropolitana da Baixada Santista/Vale do Ribeira'),
            (14, 'SP', 'São Paulo', 'Avaré/Bauru/Botucatu/Jaú/Lins/Marília/Ourinhos'),
            (15, 'SP', 'São Paulo', 'Itapetininga/Itapeva/Sorocaba/Tatuí'),
            (16, 'SP', 'São Paulo', 'Araraquara/Franca/Jaboticabal/Ribeirão Preto/São Carlos/Sertãozinho'),
            (17, 'SP', 'São Paulo', 'Barretos/Catanduva/Fernandópolis/Jales/São José do Rio Preto/Votuporanga'),
            (18, 'SP', 'São Paulo', 'Andradina/Araçatuba/Assis/Birigui/Dracena/Presidente Prudente'),
            (19, 'SP', 'São Paulo', 'Americana/Campinas/Limeira/Piracicaba/Rio Claro/São João da Boa Vista'),
            (21, 'RJ', 'Rio de Janeiro', 'Rio de Janeiro e Região Metropolitana/Teresópolis'),
            (22, 'RJ', 'Rio de Janeiro', 'Cabo Frio/Campos dos Goytacazes/Itaperuna/Macaé/Nova Friburgo'),
            (24, 'RJ', 'Rio de Janeiro', 'Angra dos Reis/Petrópolis/Volta Redonda/Piraí'),
            (27, 'ES', 'Espírito Santo', 'Vitória e Região Metropolitana/Colatina/Linhares/Santa Maria de Jetibá'),
            (28, 'ES', 'Espírito Santo', 'Cachoeiro de Itapemirim/Castelo/Itapemirim/Marataízes'),
            (31, 'MG', 'Minas Gerais', 'Belo Horizonte e Região Metropolitana/Conselheiro Lafaiete/Ipatinga/Viçosa'),
            (32, 'MG', 'Minas Gerais', 'Barbacena/Juiz de Fora/Muriaé/São João del-Rei/Ubá'),
            (33, 'MG', 'Minas Gerais', 'Almenara/Caratinga/Governador Valadares/Manhuaçu/Teófilo Otoni'),
            (34, 'MG', 'Minas Gerais', 'Araguari/Araxá/Patos de Minas/Uberlândia/Uberaba'),
            (35, 'MG', 'Minas Gerais', 'Alfenas/Guaxupé/Lavras/Poços de Caldas/Pouso Alegre/Varginha'),
            (37, 'MG', 'Minas Gerais', 'Bom Despacho/Divinópolis/Formiga/Itaúna/Pará de Minas'),
            (38, 'MG', 'Minas Gerais', 'Curvelo/Diamantina/Montes Claros/Pirapora/Unaí'),
            (41, 'PR', 'Paraná', 'Curitiba e Região Metropolitana'),
            (42, 'PR', 'Paraná', 'Ponta Grossa/Guarapuava'),
            (43, 'PR', 'Paraná', 'Apucarana/Londrina'),
            (44, 'PR', 'Paraná', 'Maringá/Campo Mourão/Umuarama'),
            (45, 'PR', 'Paraná', 'Cascavel/Foz do Iguaçu'),
            (46, 'PR', 'Paraná', 'Francisco Beltrão/Pato Branco'),
            (47, 'SC', 'Santa Catarina', 'Balneário Camboriú/Blumenau/Itajaí/Joinville'),
            (48, 'SC', 'Santa Catarina', 'Florianópolis e Região Metropolitana/Criciúma'),
            (49, 'SC', 'Santa Catarina', 'Caçador/Chapecó/Lages'),
            (51, 'RS', 'Rio Grande do Sul', 'Porto Alegre e Região Metropolitana/Santa Cruz do Sul/Litoral Norte'),
            (53, 'RS', 'Rio Grande do Sul', 'Pelotas/Rio Grande'),
            (54, 'RS', 'Rio Grande do Sul', 'Caxias do Sul/Passo Fundo'),
            (55, 'RS', 'Rio Grande do Sul', 'Santa Maria/Santana do Livramento/Santo Ângelo/Uruguaiana'),
            (61, 'DF', 'Distrito Federal/Goiás', 'Abrangência em todo o Distrito Federal e alguns municípios da Região Integrada de Desenvolvimento do Distrito Federal e Entorno'),
            (62, 'GO', 'Goiás', 'Goiânia e Região Metropolitana/Anápolis/Niquelândia/Porangatu'),
            (63, 'TO', 'Tocantins', 'Abrangência em todo o estado'),
            (64, 'GO', 'Goiás', 'Caldas Novas/Catalão/Itumbiara/Rio Verde'),
            (65, 'MT', 'Mato Grosso', 'Cuiabá e Região Metropolitana'),
            (66, 'MT', 'Mato Grosso', 'Rondonópolis/Sinop'),
            (67, 'MS', 'Mato Grosso do Sul', 'Abrangência em todo o estado'),
            (68, 'AC', 'Acre', 'Abrangência em todo o estado'),
            (69, 'RO', 'Rondônia', 'Abrangência em todo o estado'),
            (71, 'BA', 'Bahia', 'Salvador e Região Metropolitana'),
            (73, 'BA', 'Bahia', 'Eunápolis/Ilhéus/Porto Seguro/Teixeira de Freitas'),
            (74, 'BA', 'Bahia', 'Irecê/Jacobina/Juazeiro/Xique-Xique'),
            (75, 'BA', 'Bahia', 'Alagoinhas/Feira de Santana/Paulo Afonso/Valença'),
            (77, 'BA', 'Bahia', 'Barreiras/Bom Jesus da Lapa/Guanambi/Vitória da Conquista'),
            (79, 'SE', 'Sergipe', 'Abrangência em todo o estado'),
            (81, 'PE', 'Pernambuco', 'Recife e Região Metropolitana/Caruaru'),
            (82, 'AL', 'Alagoas', 'Abrangência em todo o estado'),
            (83, 'PB', 'Paraíba', 'Abrangência em todo o estado'),
            (84, 'RN', 'Rio Grande do Norte', 'Abrangência em todo o estado'),
            (85, 'CE', 'Ceará', 'Fortaleza e Região Metropolitana'),
            (86, 'PI', 'Piauí', 'Teresina e alguns municípios da Região Integrada de Desenvolvimento da Grande Teresina/Parnaíba'),
            (87, 'PE', 'Pernambuco', 'Garanhuns/Petrolina/Salgueiro/Serra Talhada'),
            (88, 'CE', 'Ceará', 'Juazeiro do Norte/Sobral'),
            (89, 'PI', 'Piauí', 'Picos/Floriano'),
            (91, 'PA', 'Pará', 'Belém e Região Metropolitana'),
            (92, 'AM', 'Amazonas', 'Manaus e Região Metropolitana/Parintins'),
            (93, 'PA', 'Pará', 'Santarém/Altamira'),
            (94, 'PA', 'Pará', 'Marabá'),
            (95, 'RR', 'Roraima', 'Abrangência em todo o estado'),
            (96, 'AP', 'Amapá', 'Abrangência em todo o estado'),
            (97, 'AM', 'Amazonas', 'Abrangência no interior do estado'),
            (98, 'MA', 'Maranhão', 'São Luís e Região Metropolitana'),
            (99, 'MA', 'Maranhão', 'Caxias/Codó/Imperatriz');

    GO
  init-basetechchallenge.sh: |
    #!/bin/bash
    # Espera até que o SQL Server esteja pronto
    until /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Teste@123 -Q "SELECT 1" &> /dev/null
    do
      echo "Aguardando o SQL Server iniciar..."
      sleep 5
    done

    # Executa os scripts SQL
    /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Teste@123 -d master -i /tmp/01-BaseTechChallenge.sql
    /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Teste@123 -d master -i /tmp/02-BaseTechChallenge.sql