apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  annotations:
    description: "API service"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: brunodasilvadev/techchallenge-api
        ports:
        - containerPort: 8080
        - containerPort: 443
        env:
        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Username
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
        - name: ASPNETCORE_URLS
          value: "https://+:443;http://+:8080"
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "false"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=TECHCHALLENGE;User Id=sa;Password=Teste@123;"
        - name: CORS__AllowedOrigins
          value: "localhost"
