apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
  annotations:
    description: "Deployment do SQL Server"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /var/opt/mssql"]
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "Teste@123"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: MSSQL_AGENT_ENABLED
              value: "true"
            - name: MSSQL_MEMORY_LIMIT_MB
              value: "512"
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "750Mi"
              cpu: "100m"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
