apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  labels:
    app: mssql
  annotations:
    description: "Persistent Volume Claim para o banco de dados MSSQL."
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
