apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    name: portahttp
  - port: 443
    targetPort: 443
    name: portahttps
  selector:
    app: api