{
 "title": "New dashboard",
 "time": { "from": "2025-02-16T19:09:56.932Z", "to": "2025-02-16T19:19:56.932Z" },
 "panels": [
  {
   "title": "Latência por requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{job=\"api\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contagem de requisições por status http",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"api\"}[15m])) by(http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"api\", otel_scope_name=\"TechChallenge.CadastroContato.Api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage_percentage {job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU (Cores)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_count {job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}