apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver
6.	PersistentVolumeClaim para SQL Server:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
