apiVersion: v1
kind: ConfigMap
metadata:
  name: techchallenge-configmap
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "DefaultConnection": "Server=banco-docker,1433;Database=TECHCHALLENGE;User Id=sa;Password=Teste@123;Encrypt=False;"
      }
    }